const script = [
    {text: "カタカタカタ...... \n 静かな研究室でキーボードの音だけが聞こえる。", bg: "bg/PC_night_ON.jpg", sound: "", choices: [], route: 1},
    {text: "「はぁー、やっと終わった」", bg: "bg/PC_night_ON.jpg", sound: "", choices: [], route: 1},
    {text: "翌日のミーティングの準備を終えた俺は大きなため息をついた。", bg: "bg/PC_night_ON.jpg", sound: "", choices: [], route: 1},
    {text: "「今日は朝から授業もあったしさすがに疲れたな」", bg: "bg/PC_night_ON.jpg", sound: "", choices: [], route: 1},
    {text: "周りを見渡すと他のメンバーは皆すでに帰宅済みで研究室には俺1人であった。", bg: "bg/PC_night_ON.jpg", sound: "", choices: [], route: 1},
    {text: "「てか今何時だ？」", bg: "bg/PC_night_ON.jpg", sound: "", choices: [], route: 1},
    {text: "手元のスマホで時間を確認してみると、22時を少し過ぎていた。", bg: ["bg/PC_night_ON.jpg", "bg/smartphone.png"], sound: "", choices: [], route: 1},
    {text: "「やば！もうこんな時間。早く帰らないと」", bg: "bg/PC_night_ON.jpg", sound: "", choices: [], route: 1},
    {text: "うちの大学では22時を過ぎて校内に無断で残るのは禁止されている。", bg: "bg/PC_night_ON.jpg", sound: "", choices: [], route: 1},
    {text: "急いで帰り支度を終えた俺は研究室の電気を消し、部屋を出た。", bg: "bg/PC_night_OFF.jpg", sound: "sound/light_swich.mp3", choices: [], route: 1},
    {text: "「さすがに暗いな」", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "廊下は消灯されており、非常灯だけが薄らと見えた。", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "俺は薄暗い廊下を進みエレベーターを目指した。", bg: "bg/corridor_night.jpg", sound: "sound/walk.wav", choices: [], route: 1},
    {text: "5月に入ったが夜はまだ少し肌寒かった。", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "「夜はまだ寒いな。上着着てくればよかった。」", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "エレベーター前に着いた俺は下へ向かうボタンを押した。", bg: "bg/elevator_OFF.jpg", sound: "", choices: [], route: 1},
    {text: "俺の研究室は7階にあるのでエレベーターが到着するまで少し時間がかかった。", bg: "bg/elevator_OFF.jpg", sound: "", choices: [], route: 1},
    {text: "「やっときた。早く帰ってお風呂に入ろ。」", bg: "bg/elevator_OFF.jpg", sound: "", choices: [], route: 1},
    {text: "エレベーターに乗り込んだ俺は1階のボタンを押してしばらくすると扉が閉まった。", bg: "bg/elevator_inside.jpg", sound: "", choices: [], route: 1},
    {text: "若干の浮遊感を感じながらエレベーターはゆっくりと下降を始めた。", bg: "bg/elevator_inside.jpg", sound: "", choices: [], route: 1},
    {text: "階を表示するパネルが1階に変わり、到着音の少し後に扉がゆっくりと開いた。", bg: "bg/elevator_inside.jpg", sound: "sound/beru.mp3", choices: [], route: 1},
    {text: "エレベーターを出たすぐ横にある扉から出ようとすると、なぜか扉がなかった。", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "「あれ？確かに1階に着いたよな...」", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "不思議に思い、エレベーター横のフロアマップを確認すると、そこには7階と記されていた。", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "「えっ...」", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "疲労のせいで寝ぼけたのかと思い、俺はもう一度エレベーターに乗り込んで1階のボタンを押した。", bg: "bg/elevator_inside.jpg", sound: "", choices: [], route: 1},
    {text: "エレベーターはさっきと同じように動き出し、到着音の後に扉が開いた。", bg: "bg/elevator_inside.jpg", sound: "sound/beru.mp3", choices: [], route: 1},
    {text: "しかし、エレベーターを降りて左右どちらを見てもそこにあるのは薄暗い廊下だけであった。", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "再度フロアマップを確認するとやはり7階と書いていた。", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "「また7階！？」", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "経験したことのない奇妙な現象に俺は少し焦り始めた。", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "「何か1階に行く方法はないか...」", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "少し考えると俺は廊下を曲がった先に階段があることを思い出した。", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "「階段なら1階に行ける！」", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "出られる期待から少し笑みがこぼれた。", bg: "bg/corridor_night.jpg", sound: "", choices: [], route: 1},
    {text: "俺は急いで廊下を進み、角を曲がってすぐの階段にたどり着いた。", bg: "bg/stair_night.jpg", sound: "", choices: [], route: 1},
    {text: "息を切らしながら階段を駆け下り、1階に続く最後の階段を降りた。", bg: "bg/stair_night.jpg", sound: "sound/run.mp3", choices: [], route: 1},
    {text: "するとそこには扉がなく、右を見るとあるはずのない下階に続く階段が存在した。", bg: "bg/stair_night.jpg", sound: "", choices: [], route: 1},
    {text: "俺はまさかと思い、フロアマップを確認すると7階を示していた。", bg: "bg/stair_night.jpg", sound: "", choices: [], route: 1},
    {text: "「はぁ！何でだよ！」", bg: "bg/stair_night.jpg", sound: "", choices: [], route: 1},
    {text: "7階から出られない恐怖から俺は苛立ちを露わにした。", bg: "bg/stair_night.jpg", sound: "", choices: [], route: 1},
    {text: "「他に方法がないか周りを見渡してみると廊下の奥に微かに光が漏れ出ている部屋が見えた。」", bg: "bg/corridor_light.jpg", sound: "", choices: [], route: 1},
    {text: "「さっき研究室出たとき明かりがついた部屋なんてあったっけ？」", bg: "bg/corridor_light.jpg", sound: "", choices: [], route: 1},
    {text: "俺は不思議に思ったが誰かいることに安堵して助けを求めることにした。", bg: "bg/corridor_light.jpg", sound: "sound/walk.wav", choices: [], route: 1},
    {text: "「どこの研究グループだろう？」", bg: "bg/corridor_light.jpg", sound: "", choices: [], route: 1},
    {text: "そう思った俺は部屋の少し手前で止まりドアの横にあるプレートを確認した。", bg: "bg/corridor_light.jpg", sound: "", choices: [], route: 1},
    {text: "「断絶回路設計研究グループ...」", bg: ["bg/corridor_light.jpg", "bg/plate.jpg"], sound: "", choices: [], route: 1},
    {text: "「そんな研究室あったっけ？」", bg: ["bg/corridor_light.jpg", "bg/plate.jpg"], sound: "", choices: [], route: 1},
    {text: "研究室の名前に疑問は感じたが今はそれどころではなかった。", bg: ["bg/corridor_light.jpg", "bg/plate.jpg"], sound: "", choices: [], route: 1},
    {text: "俺はドアをノックしてゆっくりと開けた。", bg: "bg/corridor_light.jpg", sound: "sound/knock.mp3", choices: [], route: 1},
    {text: "「失礼しまーす」", bg: "bg/corridor_light.jpg", sound: "", choices: [], route: 1},
    {text: "部屋は10畳ほどの大きさで机が4つ向かい合わせで置かれたこじんまりとした部屋だった。", bg: "bg/office.jpg", sound: "", choices: [], route: 1},
    {text: "部屋を見渡してみるが誰も居なかった。", bg: "bg/office.jpg", sound: "", choices: [], route: 1},
    {text: "「トイレにでも行ってるのかな？」", bg: "bg/office.jpg", sound: "", choices: [], route: 1},
    {text: "そう思い少しの間待ってみることにした。", bg: "bg/office.jpg", sound: "", choices: [], route: 1},
    {text: "「少し物色してみるか」", bg: "bg/office.jpg", sound: "", choices: [], route: 1},
    {text: "聞き覚えのない研究室に興味が湧き少し見てみることにした。", bg: "bg/office.jpg", sound: "", choices: [], route: 1},
    {text: "まずは本棚を見てみると見慣れた電気系の教科書が並んでいた。", bg: "bg/bookshelf.jpg", sound: "", choices: [], route: 1},
    {text: "「線形代数... 電磁気学... 確率統計...」", bg: "bg/bookshelf.jpg", sound: "", choices: [], route: 1},
    {text: "俺は過去の嫌な記憶を思いだし、身震いをした。", bg: "bg/bookshelf.jpg", sound: "", choices: [], route: 1},
    {text: "ただなぜか俺が使用していた本と同じ表紙なのに著者が異なっていた。", bg: "bg/bookshelf.jpg", sound: "", choices: [], route: 1},
    {text: "次に机を見てみると1台のパソコンが起動しており、画面にプログラムと「断絶成功」の出力結果が表示されていた。", bg: ["bg/office.jpg", "bg/program.jpg"], sound: "", choices: [], route: 1},
    {text: "「断絶成功？何のプログラムだ？」", bg: ["bg/office.jpg", "bg/program.jpg"], sound: "", choices: [], route: 1},
    {text: "俺は研究でシミュレーションをしていることもありプログラムの知識はある程度あった。", bg: ["bg/office.jpg", "bg/program.jpg"], sound: "", choices: [], route: 1},
    {text: "しかし、プログラムは見たことのない言語で記述されており、解読することができなかった。", bg: ["bg/office.jpg", "bg/program.jpg"], sound: "", choices: [], route: 1},
    {text: "他に手がかりがないかとフォルダを物色してみると「研究日誌」と書かれたフォルダを見つけた。", bg: ["bg/office.jpg", "bg/program.jpg"], sound: "", choices: [], route: 1},
    {text: "フォルダをクリックして開くと去年からの日付が記されたテキストファイルが大量に現れた。", bg: "", sound: "sound/click.mp3", choices: [], route: 1},
    {text: "俺はとりあえず一番古い5月12日のファイルを開いた。", bg: "", sound: "sound/click.mp3", choices: [], route: 1},
    {text: "2024/5/12 \n 今日から中野教授との空間断絶回路の研究が始まった。詳しい内容はまだ理解できていないが20年以上前から研究しているみたいだ。...", bg: "", sound: "", choices: [], route: 1},
    {text: "「中野教授？聞いたことない名前だな。」", bg: "", sound: "", choices: [], route: 1},
    {text: "俺は読み終わったファイルを閉じ、フォルダ内をスクロールして適当にもうひとつのファイルを開いた。", bg: "", sound: "sound/click.mp3", choices: [], route: 1},
    {text: "2024/11/17 \n ", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
    {text: "", bg: "", sound: "", choices: [], route: 1},
  ];
// {text: "", bg: "", sound: "", choices: [], route: 1},